pipeline {
    agent any

    environment {
        SERVER_IP = credentials('app-server-ip')
        username = "ubuntu"
        dest_path= "/home/ubuntu/"
        folder = "/02-single-server-deployment"
    }
    stages {

        // stage('Create virtualenv') {
        //     steps {
        //         sh "python3 -m venv venv"
        //         sh ". ./venv/bin/activate" 
        //     }
        // }

        stage('Setup and Test') {
            agent {
                docker {
                    image 'python:3.10-alpine'
                }
            }

            steps {
                sh """
                python3 -m venv venv
                . venv/bin/activate
                pip install -r .${folder}/requirements.txt
                pytest
                """
            }


        } 
        
        // stage('Test') {
        //     steps {    
        //         sh "pytest"  
        //     }
        // }

        stage('Package code') {      
            steps {   
                sh """
                zip -r myapp.zip .${folder}/* -x '*.git*'
                ls -lart
                """
            }
        }

        stage('Deploy to App Server') {
            steps {
                script {
                    sshagent(['app-server-ssh-access']) {
                        sh """
                            scp -o StrictHostKeyChecking=no myapp.zip  ${username}@${SERVER_IP}:${dest_path}
                            ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                                rm -rf ${dest_path}/app/*
                                unzip -o ${dest_path}/myapp.zip -d ${dest_path}/app/
                                source ${dest_path}/app/venv/bin/activate
                                cd ${dest_path}/app/
                                pip install -r requirements.txt
                                sudo systemctl restart app.service
                            "
                        """
                    }
                }
            } 
        }
        
    }
}