pipeline {
    agent any

    environment {
        SERVER_IP = credentials('app-server-ip')
        username = "ubuntu"
        dest_path= "/home/ubuntu"
        folder = "/02-single-server-deployment"
    }
    stages {

        stage('Setup') {
            agent {
                docker {
                    image 'python:3.10-alpine'
                }
            }

            steps {
                dir("${WORKSPACE}${folder}") {
                    sh """
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    """
                }
            }
        }

        stage('Test') {
            agent {
                docker {
                    image 'python:3.10-alpine'
                }
            }

            steps {
                dir("${WORKSPACE}${folder}") {
                    sh """
                    . venv/bin/activate
                    pytest
                    """
                }
            }
        }
         

        stage('Package code') {      
            steps {  
                dir("${WORKSPACE}${folder}") { 
                    sh """
                    zip -r myapp.zip ./* -x '*.git*'
                    ls -lart
                    unzip -l myapp.zip
                """
                }
            }
        }

        stage('Deploy to App Server') {
            steps {
                script {
                    sshagent(['app-server-ssh-access']) {
                        sh """
                            scp -o StrictHostKeyChecking=no ${WORKSPACE}${folder}/myapp.zip  ${username}@${SERVER_IP}:${dest_path}
                            ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                                rm -rf ${dest_path}/app/*
                                unzip -o ${dest_path}/myapp.zip -d ${dest_path}/app/
                                python3 -m venv ${dest_path}/app/venv
                                . ${dest_path}/app/venv/bin/activate
                                cd ${dest_path}/app/
                                pip install -r requirements.txt
                                sudo systemctl restart app.service
                            "
                        """
                    }
                }
            } 
        }
        
    }
}