pipeline {
    agent any

    environment {
        SERVER_IP = credentials('app-server-ip')
    }
    stages {
        stage('Setup') {
            steps {
                sh "pip install -r requirements.txt"
            }
        }
        stage('Test') {
            steps {    
                sh "pytest"
            }
        }

        stage('Package code') {      
            steps {
                sh "zip -r myapp.zip ./* -x '*.git*'"
                sh "ls -lart"
            }
        }

        stage('Deploy to App Server') {
            when {
                branch "feature"
            }
            steps {
                script {
                    sshagent(['app-server-private-key']) {
                        sh """
                            ssh -o StrictHostKeyChecking=no ubuntu@${SERVER_IP} "
                                sudo systemctl stop flaskapp.service
                                rm -rf /home/ubuntu/app/*
                                unzip -o /home/ubuntu/myapp.zip -d /home/ubuntu/app/
                                source app/venv/bin/activate
                                cd /home/ubuntu/app/
                                pip install -r requirements.txt
                                sudo systemctl start flaskapp.service
                            "
                        """
                    }
                }
            } 
        }
        
    }
}